# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0.6

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run tests!
      - run:
          name: Test
          command: mvn test

  deployment:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0.6

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run deployment!
      - run:
          name: Deploy
          command: mvn deploy -Dmaven.test.skip -DcreateDocs=true -s settings.xml
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build
